apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-kube-prometheus-kube-prome-alertmanager
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'tyagilavit25@gmail.com'        # tumhara Gmail
      smtp_auth_username: 'tyagilavit25@gmail.com'
      smtp_auth_password: 'inka sgec wgph eeeg'  # Gmail App Password 
      smtp_require_tls: true

    route:
      group_by: ['alertname', 'severity']
      group_wait: 30s        # pehla alert kitni der baad bheje
      group_interval: 5m     # same group ka next alert
      repeat_interval: 12h   # same alert dobara kitni der baad bheje
      receiver: 'email-alerts'

    receivers:
    - name: 'email-alerts'
      email_configs:
      - to: 'tyagilavit25@gmail.com'             # kahan receive karna hai
        send_resolved: true                    # jab alert theek ho tab bhi email aaye